name: Sync

on:
  workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v7

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Clean Models
        run: rm -rf src/Models/*/crds

      - name: Clean Cs
        run: rm -rf src/Models/*/Generated

      - name: Sync CRDs
        run: dotnet run --project src/KubernetesCRDModelGen.Sync/KubernetesCRDModelGen.Sync.csproj --RootDirectory=$PWD

      - name: Validate Yamls
        shell: pwsh
        run: |
          foreach ($Dir in Get-ChildItem -Directory -Path src/Models) {
            $YamlFiles = Get-ChildItem -Path $($Dir.FullName + "/crds/") -Filter *.yaml -File -ErrorAction SilentlyContinue

            if ($YamlFiles -eq $null -or $YamlFiles.Count -eq 0) {
              throw "No .yaml file found in directory: $($Dir.FullName)"
            }
          }

      - name: Build
        run: dotnet build

      - name: Validate Cs
        shell: pwsh
        run: |
          foreach ($Dir in Get-ChildItem -Directory -Path src/Models) {
            $CsFiles = Get-ChildItem -Path $($Dir.FullName + "/Generated/") -Filter *.cs -File -Recurse -ErrorAction SilentlyContinue

            if ($CsFiles -eq $null -or $CsFiles.Count -eq 0) {
              throw "No .cs file found in directory: $($Dir.FullName)"
            }
          }

      - name: Check Files Changed
        id: checkfiles
        shell: pwsh
        run: |
          git add .
          $createPR = (git diff --cached --numstat | Measure-Object -Line).Lines -gt 0;
          echo "createpr=$createPR" >> $env:GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.checkfiles.outputs.createpr == 'True'
        id: cpr
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GH_PAT }}
          branch: sync-charts
          commit-message: "feat: Sync"
          title: "feat: Sync"
          body: "Automated CRD Sync"

      - name: Enable Pull Request Automerge
        if: steps.checkfiles.outputs.createpr == 'True'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GH_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
